const Message = {};
Message.somethingWentWrong = "Something went wrong";
Message.successfullySubmitted = "Successfully Submitted";
Message.successfullyLoggedIn = "Successfully Logged In";
Message.updatedSuccessfully = "Update Successfully";
Message.successfullyFetched = "Successfully Fetched";
Message.unAuthorized = "You are not Authorized";
Message.tokenMissing = "Token is Missing";
module.exports = Message;
